default: &default
  adapter: mysql2
  encoding: utf8
  database: myapp_development
  # host: db
  # PasswordとUsernameはdocker-compose.ymlと合わせます
  username: root
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # pool: 5
  socket: /var/run/mysqld/mysqld.sock
  

development:
  <<: *default
  database: myapp_development


test:
  <<: *default
  database: myapp_test
  
production:
  <<: *default
  database: myapp_production
  username: myapp
  password: 